swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /transaction:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Get all transactions
            description: API for fetching all transactions
            parameters:
                - in: header
                  type: string
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
            responses:
                "200":
                    description: Transactions retrieved successully
                    schema:
                        $ref: "#/definitions/Transaction"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction/{transactionId}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Find transaction by ID
            description: Return a single transaction
            parameters:
                - in: header
                  type: string
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                - in: path
                  name: transactionId
                  description: ID of transaction to return
                  required: true
                  type: integer
            responses:
                "200":
                    description: Transaction retrieved successully
                    schema:
                        $ref: "#/definitions/TransactionDetail"
                "401":
                    description: Unauthorized
                "404":
                    description: Not Found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Update an existing transaction
            description: Update an existing transaction by ID
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  type: string
                  required: true
                - in: path
                  name: transactionId
                  description: ID of transaction to return
                  required: true
                  type: integer
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: "#/definitions/UpdateTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction updated syccessfully
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction doesn't exist
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    Transaction:
        properties:
            date:
                type: string
                format: date
                description: transaction date
            description:
                type: string
                description: transaction description
            amount:
                type: number
                description: transaction amount
            balance:
                type: number
                description: account balance after transaction
    TransactionDetail:
        properties:
            date:
                type: string
                format: date
                description: transaction date
            description:
                type: string
                description: transaction description
            amount:
                type: number
                description: transaction amount
            balance:
                type: number
                description: account balance after transaction
            type:
                type: string
                description: transaction type
            category:
                type: string
                description: transaction category
            notes:
                type: string
                description: transaction notes
    UpdateTransaction:
        properties:
            category:
                type: string
                description: transaction category
            notes:
                type: string
                description: transaction notes
